# Generated by Django 5.2 on 2025-05-06 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المخزن')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='رمز المنتج')),
                ('quantity', models.FloatField(default=0, verbose_name='الكمية الكلية')),
                ('unit', models.CharField(max_length=50, verbose_name='الوحدة')),
                ('min_stock', models.FloatField(verbose_name='الحد الأدنى للمخزون')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='auth.group', verbose_name='الفريق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_added_by', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('new_product', 'New Product'), ('quantity_added', 'Quantity Added'), ('quantity_withdrawn', 'Quantity Withdrawn')], max_length=20, verbose_name='نوع الإشعار')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.product', verbose_name='المنتج')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('استلام', 'استلام'), ('سحب', 'سحب')], max_length=50, verbose_name='نوع الحركة')),
                ('quantity', models.FloatField(verbose_name='الكمية')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('quantity_after', models.FloatField(blank=True, null=True, verbose_name='الكمية بعد الحركة')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='auth.group', verbose_name='الفريق')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product', verbose_name='المنتج')),
            ],
        ),
        migrations.CreateModel(
            name='ProductWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='الكمية في المخزن')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product', verbose_name='المنتج')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouse', verbose_name='المخزن')),
            ],
            options={
                'unique_together': {('product', 'warehouse')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warehouses',
            field=models.ManyToManyField(related_name='products', through='myapp.ProductWarehouse', to='myapp.warehouse', verbose_name='المخازن'),
        ),
    ]
