# Generated by Django 5.2 on 2025-05-09 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_productwarehouse_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.warehouse', verbose_name='المخزن'),
        ),
    ]
