# Generated by Django 5.2 on 2025-05-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_movement_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية'),
        ),
    ]
