# Generated by Django 5.2 on 2025-05-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_movement_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='stock_after_movement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الكمية بالمخزون بعد الحركة'),
        ),
    ]
