# Generated by Django 5.2 on 2025-05-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_movement_stock_after_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='current_stock_at_movement',
            field=models.IntegerField(blank=True, null=True, verbose_name='الرصيد الحالي بالمخزن وقت الحركة'),
        ),
        migrations.AddField(
            model_name='movement',
            name='total_stock_at_movement',
            field=models.IntegerField(blank=True, null=True, verbose_name='الرصيد الكلي وقت الحركة'),
        ),
    ]
